version: '3.4'
services:
  postgres:
    image: aa8y/postgres-dataset:all
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres

  app_unit:
    build:
      context: ./
      dockerfile: ./unit-data/Dockerfile
    depends_on:
      - postgres
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: '1000M'

  app_puma:
    build:
      context: ./
      dockerfile: ./puma/Dockerfile
    command: bundle exec rails s -p 3000 -b 0.0.0.0
    depends_on:
      - postgres
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: '1000M'

  tank_unit:
    image: direvius/yandex-tank
    volumes:
      - ./tank/load_unit.yaml:/var/loadtest/load.yaml
      - ./tank/token.txt:/var/loadtest/token.txt

  tank_puma:
    image: direvius/yandex-tank
    volumes:
      - ./tank/load_puma.yaml:/var/loadtest/load.yaml
      - ./tank/token.txt:/var/loadtest/token.txt







